Let's explore pandas!

We'll start with getting some data. First we need to tell the notebook we're using pandas, then we can read in data. 

There are many ways to get your data into a dataframe. You can read it in from a link, a file on your computer, or even through a database connection (not covered here, but I recommend SQLAlchemy). [This](https://pandas.pydata.org/pandas-docs/stable/io.html) is the pandas documentation for data input/output.

The data I'm going to use is from the [Ames Housing Dataset](https://ww2.amstat.org/publications/jse/v19n3/decock.pdf).

In [7]:
import pandas as pd

df = pd.read_table("https://ww2.amstat.org/publications/jse/v19n3/decock/AmesHousing.txt")
# we can check if it loaded properly using head() and tail()
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [8]:
df.tail(20)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
2910,2911,923225260,160,RM,42.0,3964,Pave,NaN,Reg,Lvl,...,0,NaN,GdPrv,NaN,0,6,2006,WD,Normal,151400
2911,2912,923225510,20,RL,58.0,10172,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,10,2006,WD,Normal,126500
2912,2913,923226150,90,RL,NaN,11836,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,3,2006,WD,Normal,146500
2913,2914,923226180,180,RM,21.0,1470,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,73000
2914,2915,923226290,160,RM,21.0,1484,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,79400
2915,2916,923227100,20,RL,80.0,13384,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,140000
2916,2917,923228130,180,RM,21.0,1533,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,8,2006,WD,Abnorml,92000
2917,2918,923228180,160,RM,21.0,1533,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,12,2006,WD,Abnorml,87550
2918,2919,923228210,160,RM,21.0,1526,Pave,NaN,Reg,Lvl,...,0,NaN,GdPrv,NaN,0,6,2006,WD,Normal,79500
2919,2920,923228260,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,90500
2920,2921,923228310,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,71000
2921,2922,923229110,90,RL,55.0,12640,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,150900
2922,2923,923230040,90,RL,63.0,9297,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,7,2006,WD,Family,188000
2923,2924,923250060,20,RL,80.0,17400,Pave,NaN,Reg,Low,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,160000
2924,2925,923251180,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,131000
2925,2926,923275080,80,RL,37.0,7937,Pave,NaN,IR1,Lvl,...,0,NaN,GdPrv,NaN,0,3,2006,WD,Normal,142500
2926,2927,923276100,20,RL,NaN,8885,Pave,NaN,IR1,Low,...,0,NaN,MnPrv,NaN,0,6,2006,WD,Normal,131000
2927,2928,923400125,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,132000
2928,2929,924100070,20,RL,77.0,10010,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,170000
2929,2930,924151050,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,188000

In [9]:
df.shape # this tells us (number of rows, number of columns)

(2930, 82)

In [10]:
df.columns # prints a list of the columns in the database

Index(['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style',
       'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type',
       'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
       'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional',
       'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt',
       'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF',
       'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC',
       'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type',
       'Sale Condition', 'SalePrice'],
      dtype='object')

Let's use this data to find which variables have the greatest effect on SalePrice. First, let's take a look at the nature of the sale price.

In [11]:
df['SalePrice'].describe()

count      2930.000000
mean     180796.060068
std       79886.692357
min       12789.000000
25%      129500.000000
50%      160000.000000
75%      213500.000000
max      755000.000000
Name: SalePrice, dtype: float64

What if we think 3 season porches aren't that important when determining the sale price? We could drop that column.

In [12]:
df = df.drop('3Ssn Porch', axis=1)
df.columns

Index(['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style',
       'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type',
       'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
       'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional',
       'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt',
       'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF',
       'Enclosed Porch', 'Screen Porch', 'Pool Area', 'Pool QC', 'Fence',
       'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type',
       'Sale Condition', 'SalePrice'],
      dtype='object')

We can also add columns with some help from numpy. Maybe we decide that what's more important than the number of fireplaces is simply whether there is a fireplace at all. We can add a boolean for fireplace.

In [13]:
import numpy as np

df['fireplace?'] = np.where(df['Fireplaces'] > 0, 1, 0)
df['fireplace?'].head()

0    1
1    0
2    0
3    1
4    1
Name: fireplace?, dtype: int64

Let's make a hypothesis about which features have the greatest effect on the sale price of a home and try a linear regression model. You can do this with scikit-learn.

In [14]:
from sklearn import linear_model

X_cols = df[['SalePrice','SalePrice','Full Bath','Half Bath','Lot Area','1st Flr SF','2nd Flr SF','TotRms AbvGrd']]
linear_sk = linear_model.LinearRegression()
result_sk = linear_sk.fit(X_cols, df['SalePrice'])
print(linear_sk.coef_)
print(linear_sk.intercept_)

[  5.00000000e-01   5.00000000e-01   9.87136154e-13   4.81417771e-13
  -1.11022302e-16  -1.84314369e-17   1.04300249e-16  -1.20910005e-13]
1.16415321827e-10

If you're looking for something closer to what you'd find in STATA or SPSS, personally I love the output from statsmodels.

In [15]:
import statsmodels.api as sm

linear_sm = sm.OLS(df['SalePrice'],X_cols)
result_sm = linear_sm.fit()
print(result_sm.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 1.841e+32
Date:                Tue, 12 Sep 2017   Prob (F-statistic):               0.00
Time:                        20:34:49   Log-Likelihood:                 60112.
No. Observations:                2930   AIC:                        -1.202e+05
Df Residuals:                    2923   BIC:                        -1.202e+05
Df Model:                           7
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [95.0% Conf. Int.]
---------------------------------------------------------------------------------
SalePrice         0.5000   5.57e-17   8.98e+15      0.000         0.500     0.500
SalePrice         0.5000   5.57e-17   8.98e+15      0.000         0.500     0.500
Full Bath      1.455e-11   1.31e-11      1.113      0.266     -1.11e-11  4.02e-11
Half Bath      4.547e-12   1.43e-11      0.318      0.751     -2.35e-11  3.26e-11
Lot Area       -1.11e-15   7.49e-16     -1.482      0.139     -2.58e-15  3.59e-16
1st Flr SF     2.576e-14    2.8e-14      0.921      0.357     -2.91e-14  8.06e-14
2nd Flr SF     1.776e-15   2.55e-14      0.070      0.945     -4.83e-14  5.18e-14
TotRms AbvGrd -5.002e-12   4.71e-12     -1.063      0.288     -1.42e-11  4.23e-12
==============================================================================
Omnibus:                     1173.032   Durbin-Watson:                   0.135
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             6989.293
Skew:                          -1.797   Prob(JB):                         0.00
Kurtosis:                       9.658   Cond. No.                     1.01e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.25e-18. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

Statsmodels gives a nice output similar to what you would find in STATA, SPSS or other statistical software packages.

Many other examples in both statsmodels and scikit-learn follow the same process:
1. Declare the model.
2. Fit the model to your data.
3. Print the results for inspection.

I hope this has helped you get started using pandas dataframes. Any questions?